CREATE DATABASE CarHubDB
GO

USE CarHubDB
GO

CREATE TABLE carhub(
	CarID INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	CarBrand NVARCHAR(100) NOT NULL,
	CarModel NVARCHAR(100) NOT NULL,
	CarYear NVARCHAR(100) NOT NULL,
	CarOwner NVARCHAR(100) NOT NULL
)

SELECT * FROM carhub